---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: splunk-pv-volume
  namespace: splunk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/splunk-hsbc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-claim
  namespace: splunk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: splunk
  name: splunk
  namespace: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
      io.kompose.service: splunk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: splunk
        io.kompose.service: splunk
    spec:
      containers:
        - name: splunk
          image: splunk/splunk
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_PASSWORD
              value: "Password@1"
#            - name: SPLUNK_USER
#              value: root
          ports:
            - containerPort: 8000
              name: ui
            - containerPort: 8065
              name: app-server
            - containerPort: 8088
              name: hec
            - containerPort: 8089
              name: management
            - containerPort: 9997
              name: receiving
          volumeMounts:
            - mountPath: /opt/splunk/etc/apps
              name: splunk
          resources: {}
      restartPolicy: Always
      volumes:
        - name: splunk
          persistentVolumeClaim:
            claimName: splunk-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  #creationTimestamp: null
  labels:
    app: splunk
    io.kompose.service: splunk
  name: splunk
  namespace: splunk
spec:
  type: NodePort
  ports:
    - name: "ui"
      nodePort: 30008
      port: 8000
      targetPort: 8000
    - name: "hec"
      nodePort: 30088
      port: 8088
      targetPort: 8088
    - name: "receiving"
      nodePort: 30097
      port: 9997
      targetPort: 9997
  selector:
    app: splunk
    io.kompose.service: splunk
status:
  loadBalancer: {}
---