version: '3.8'

services:
    splunk:
        image: splunk/splunk:latest
        restart: always
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: password
            SPLUNK_USER: root
        ports:
            - 8000:8000
            - 8088:8088
            - 8089:8089
#        volumes:
#            - ./hsbc_wpb_acs:/opt/splunk/etc/apps/hsbc_wpb_acs