apiVersion: v1
kind: Secret
metadata:
  name: xagent-keys
  namespace: mem-leak-java  
type: Opaque
data:
  WEBSOCKET_SECRET: RHQwclBGWFNWSjc4dTZLZmlveG80Q3JONk5oUXp1S2M5MUtqREpZbHZ1Y2dxSzBm
  OWNER_API_KEY: NTVjNTg0MWYtZDI5MS00MDZjLWIxODItM2VlZWVmOGYzZGNk
