
---
kind: Namespace
apiVersion: v1
metadata:
  #name: venafi
  name: mem-leak-java
  labels:
    app: venafi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: venafi
  name: venafi
  #namespace: venafi
  namespace: mem-leak-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venafi
      io.kompose.service: venafi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: venafi
        io.kompose.service: venafi
    spec:
      containers:
        - name: venafi
          image: jeveenj/venafi-cert-renew:latest
          resources: {}
      restartPolicy: Always
status: {}
