---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mem-leak-java
  name: mem-leak-java
  namespace: mem-leak-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-leak-java
      io.kompose.service: mem-leak-java
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mem-leak-java
        io.kompose.service: mem-leak-java
    spec:
      containers:
        - name: mem-leak-java
          image: jeveenj/mem-leak-java:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
      restartPolicy: Always
status: {}
